# version: '3.8'

# services:
#   mongodb:
#     image: mongo:6.0
#     container_name: mean-mongo
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo-data:/data/db
#     restart: always

#   backend:
#     build: ./backend
#     container_name: mean-backend
#     ports:
#       - "8080:8080"
#     environment:
#       - MONGO_URI=mongodb+srv://ankulmaurya88:coRU4t3S2upJOztC@cluster0.o9oojii.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
#     depends_on:
#       - mongodb
#     restart: always

#   frontend:
#     build: ./frontend
#     container_name: mean-frontend
#     ports:
#       - "80:80"
#     depends_on:
#       - backend
#     restart: always

# volumes:
#   mongo-data:


version: "3.9"

services:
  frontend:
    build: ./frontend
    image: your-dockerhub-username/frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    image: your-dockerhub-username/backend:latest
    ports:
      - "8080:8080"
